[package]
name = "e621-watcher"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "*", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
futures = { version = "*", features = ["thread-pool"] }
hamming = "0.1.3"

serde = "*"
serde_json = "*"

tokio-postgres = { version = "0.5.1", features = ["with-serde_json-1"] }
bb8 = { git = "https://github.com/khuey/bb8.git" }
bb8-postgres = { git = "https://github.com/khuey/bb8.git" }

furaffinity-rs = { git = "https://github.com/Syfaro/furaffinity-rs.git" }
image = "0.23"
img_hash = "*"

[profile.dev.package."*"]
opt-level = 2
